"""allow_guest_access_nullable_user

Revision ID: 687df0c4a32d
Revises: fa906b77788a
Create Date: 2026-01-13 17:03:12.322449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687df0c4a32d'
down_revision = 'fa906b77788a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anon_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_chat_session_anon_id'), ['anon_id'], unique=False)

    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_session_anon_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('anon_id')

    # ### end Alembic commands ###
