"""Add rationale to ScanHistory

Revision ID: c8522a48af9a
Revises: 687df0c4a32d
Create Date: 2026-01-15 09:03:46.562283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8522a48af9a'
down_revision = '687df0c4a32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('scan_history', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('rationale', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=512), nullable=True))
        batch_op.create_unique_constraint('uq_user_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('google_id')

    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_column('rationale')

    # ### end Alembic commands ###
